name: Build and deploy stacks

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        role-to-assume: arn:aws:iam::017059319575:role/GitHubOicdBootstrapAppRole
        aws-region: us-east-1
    - run: npm ci
    - run: npm run build
    - run: npm run cdk -- synth
    - run: npm run cdk -- deploy --ci --all --require-approval=never
